sudo: required

language: bash

services:
  - docker

before_install:
  # generate environment file so we can give the travis environment to our test container
  - env | grep TRAVIS_ > travis.env
  - echo "GRADLE_OPTS=-Dorg.gradle.native=false" >> travis.env
  - echo "CI_NAME=travis_ci" >> travis.env
  - echo "CI=true" >> travis.env
  - echo "TRAVIS=true" >> travis.env
  - echo "CONTINUOUS_INTEGRATION=true" >> travis.env
  - echo "DEBIAN_FRONTEND=noninteractive" >> travis.env
  - echo "HAS_JOSH_K_SEAL_OF_APPROVAL" >> travis.env
  - echo $SPARK_VERSION >> travis.env

script:
  - docker network create sparkplug-test
  - docker run -d --name sparkplug-rabbitmq -P gonkulatorlabs/rabbitmq
  - docker build -t uncharted/sparkplug-test .
  - docker run --env-file travis.env -v $(pwd):/opt/sparkplug --link sparkplug-rabbitmq:sparkplug-rabbitmq --rm uncharted/sparkplug-test ./gradlew test coveralls
