rabbitmq:
  image: tutum/rabbitmq
  ports:
    - 5672:5672
    - 15672:15672
  environment:
    - RABBITMQ_PASS=sparkplug

sparkmaster:
  build: spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h sparkmaster
  hostname: sparkmaster
  environment:
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf:/conf/master
    - ./data:/tmp/data
    - ..:/opt/sparkplug
  links:
    - rabbitmq

sparkworker:
  build: spark
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077
  hostname: sparkworker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 2g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data
    - ..:/opt/sparkplug
  links:
    - sparkmaster
    - rabbitmq
  environment:
    - "affinity:container==sparkmaster"